//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A5_Q2_.MsgService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MsgService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendMsg", ReplyAction="http://tempuri.org/IService1/sendMsgResponse")]
        void sendMsg(string sendUser, string Username, string Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendMsg", ReplyAction="http://tempuri.org/IService1/sendMsgResponse")]
        System.Threading.Tasks.Task sendMsgAsync(string sendUser, string Username, string Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveMsg", ReplyAction="http://tempuri.org/IService1/receiveMsgResponse")]
        string[] receiveMsg(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveMsg", ReplyAction="http://tempuri.org/IService1/receiveMsgResponse")]
        System.Threading.Tasks.Task<string[]> receiveMsgAsync(string UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : A5_Q2_.MsgService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<A5_Q2_.MsgService.IService1>, A5_Q2_.MsgService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void sendMsg(string sendUser, string Username, string Message) {
            base.Channel.sendMsg(sendUser, Username, Message);
        }
        
        public System.Threading.Tasks.Task sendMsgAsync(string sendUser, string Username, string Message) {
            return base.Channel.sendMsgAsync(sendUser, Username, Message);
        }
        
        public string[] receiveMsg(string UserID) {
            return base.Channel.receiveMsg(UserID);
        }
        
        public System.Threading.Tasks.Task<string[]> receiveMsgAsync(string UserID) {
            return base.Channel.receiveMsgAsync(UserID);
        }
    }
}
